pizza:
  name:
    endpoint: http://localhost:9090

springfox:
  documentation:
    swagger.v2.path: /api-docs
server:
  port: 8081
  contextPath: /v1
spring:
  application:
    name: pizza-menu-facade
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
      base-path: /
      path-mapping:
        prometheus: /metrics

logging.level.root: INFO

opentracing:
  jaeger:
    enabled: true