/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.gabrielsson.api;

import com.gabrielsson.model.Ingredient;
import java.util.List;
import com.gabrielsson.model.Pizza;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@Api(value = "menu", description = "the menu API")
public interface MenuApi {

    @ApiOperation(value = "create a menu", nickname = "menuPost", notes = "Create all available pizzas with names", response = Pizza.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Pizza.class, responseContainer = "List") })
    @RequestMapping(value = "/menu",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<List<Pizza>> menuPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody List<Ingredient> body);

}
